#!/bin/bash

#/opt/stack/etcd/etcd-v2.2.2-linux-amd64/etcd --data-dir /opt/stack/etcd/db.etcd --advertise-client-urls http://0.0.0.0:4001  --listen-client-urls http://0.0.0.0:4001 >> /opt/stack/logs/etcd-server.log 2>&1 &

#sudo /usr/bin/docker daemon -H tcp://0.0.0.0:2375 --cluster-store etcd://localhost:4001 >> /opt/stack/logs/docker-engine.log 2>&1 &

#sudo PYTHONPATH=:/opt/stack/kuryr SERVICE_USER=admin SERVICE_PASSWORD=labstack SERVICE_TENANT_NAME=admin SERVICE_TOKEN=labstack IDENTIY_URL=http://127.0.0.1:5000/v2.0 python /opt/stack/kuryr/scripts/run_server.py  --config-file /etc/kuryr/kuryr.conf >> /opt/stack/logs/kuryr.log 2>&1 &

sudo ./scripts/run_kuryr.sh >> /opt/stack/logs/kuryr.log 2>&1 &

sudo service docker restart >> /opt/stack/logs/docker-restart.log 2>&1 &

/usr/local/bin/glance-registry --config-file=/etc/glance/glance-registry.conf >> /opt/stack/logs/g-reg.log 2>&1 &

/usr/local/bin/glance-api --config-file=/etc/glance/glance-api.conf >> /opt/stack/logs/g-api.log 2>&1 &

/usr/local/bin/nova-api >> /opt/stack/logs/n-api.log 2>&1 &

/usr/local/bin/neutron-server --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini >> /opt/stack/logs/q-svc.log 2>&1 &

/usr/local/bin/neutron-openvswitch-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini >> /opt/stack/logs/q-agt.log 2>&1 &

/usr/local/bin/neutron-dhcp-agent --config-file /etc/neutron/neutron.conf --config-file=/etc/neutron/dhcp_agent.ini >> /opt/stack/logs/q-dhcp.log 2>&1 &

/usr/local/bin/neutron-l3-agent --config-file /etc/neutron/neutron.conf --config-file=/etc/neutron/l3_agent.ini >> /opt/stack/logs/q-l3.log 2>&1 &

/usr/local/bin/neutron-metadata-agent --config-file /etc/neutron/neutron.conf --config-file=/etc/neutron/metadata_agent.ini >> /opt/stack/logs/q-meta.log 2>&1 &

/usr/local/bin/nova-conductor --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-cond.log 2>&1 &

/usr/local/bin/nova-cert --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-crt.log 2>&1 &

/usr/local/bin/nova-scheduler --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-sch.log 2>&1 &

/usr/local/bin/nova-spicehtml5proxy --config-file /etc/nova/nova.conf --web /usr/share/spice-html5 >> /opt/stack/logs/n-spice.log 2>&1 &

/usr/local/bin/nova-consoleauth --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-cauth.log 2>&1 &

/usr/local/bin/nova-serialproxy --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-sproxy.log 2>&1 &

/usr/local/bin/nova-objectstore --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-obj.log 2>&1 &

/usr/local/bin/nova-compute --config-file /etc/nova/nova.conf >> /opt/stack/logs/n-cpu.log 2>&1 &

/usr/local/bin/cinder-api --config-file /etc/cinder/cinder.conf >> /opt/stack/logs/c-api.log 2>&1 &

/usr/local/bin/cinder-scheduler --config-file /etc/cinder/cinder.conf >> /opt/stack/logs/c-sch.log 2>&1 &

/usr/local/bin/cinder-backup --config-file /etc/cinder/cinder.conf >> /opt/stack/logs/c-bak.log 2>&1 &

/usr/local/bin/cinder-volume --config-file /etc/cinder/cinder.conf >> /opt/stack/logs/c-vol.log 2>&1 &

/usr/local/bin/heat-engine --config-file=/etc/heat/heat.conf >> /opt/stack/logs/h-eng.log 2>&1 &

/usr/local/bin/heat-api --config-file=/etc/heat/heat.conf >> /opt/stack/logs/h-api.log 2>&1 &

/usr/local/bin/heat-api-cfn --config-file=/etc/heat/heat.conf >> /opt/stack/logs/h-api-cfn.log 2>&1 &

/usr/local/bin/heat-api-cloudwatch --config-file=/etc/heat/heat.conf >> /opt/stack/logs/h-api-cw.log 2>&1 &
